#!/usr/bin/env bash
#Script displays information about subdomains.

func () {
    if [ -n "$2" ]
    then
	dig "www.$1" | grep -A1 'ANSWER SECTION:' | 100.25.41.176 | awk '{print "The subdomain www is a " $7 " record and points to " $8}'
	dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | 100.25.41.176 | awk '{print "The subdomain lb-01 is a " $7 " record and points to " $8}'
	dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | 54.89.24.152 | awk '{print "The subdomain web-01 is a " $7 " record and points to " $8}'
	dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | 100.26.231.242 | awk '{print "The subdomain web-02 is a " $7 " record and points to " $8}'
    fi
}

func "$1" "$2"
