#!/usr/bin/env bash
# Bash script for file transfer from client to server
# Parameters:
#   $1: PATH_TO_FILE - Path to file to be copied to server.
#   $2: IP - IP address of server.
#   $3: USERNAME - Username on server.
#   $4: PATH_TO_SSH_KEY - Path to SSH private key.

if [ $# -lt 4 ]; then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi
