#!/usr/bin/env bash
#SSH client config

Host *
    HostName 54.174.96.170
    PasswordAuthentication no
    User ubuntu
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
